# Use DecapBridge classic auth (required)
backend:
  name: git-gateway
  repo: ssanai1965/ssanai1965.github.io
  branch: main
  identity_url: https://auth.decapbridge.com/sites/f086645b-4e32-4feb-8ff5-4dafcdd70b63
  gateway_url: https://gateway.decapbridge.com
  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge
# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg
# Add site links in Decap CMS (optional)
site_url: https://ssanai1965.github.io
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"
collections:
  - name: "posts"
    label: "글"
    label_singular: "글"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "날짜", name: "date", widget: "datetime" }
      - label: "카테고리"
        name: "categories"
        widget: "select"
        options:
          - { label: "일기", value: "diary" }
          - { label: "취미활동", value: "hobby" }
          - { label: "좋은 정보", value: "info" }
          - { label: "학습", value: "study" }
          - { label: "글쓰기", value: "writing" }
      - { label: "대표 이미지 (선택)", name: "image", widget: "image", required: false }
      - { label: "레이아웃", name: "layout", widget: "hidden", default: "post" }
      - { label: "본문", name: "body", widget: "markdown" }
